### ISSUE TITLE
Failed to install on windows 32-bit using  python 3.8

### ISSUE THREAD

**Issue by jcfr** [CastXML/CastXML-python-distributions#5]
from @billhoffman
```
pip install CastXML
Collecting CastXML
ERROR: Could not find a version that satisfies the requirement CastXML (from versions: none)
Collecting castxml
ERROR: Could not find a version that satisfies the requirement castxml (from versions: none)
$ pip --version
pip 19.2.3 from c:\python\lib\site-packages\pip (python 3.8)
```

```
C:\Python>python.exe
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by billhoffman** [comment]
I guess this is a known issue in the FAQ, but I think this is the default python installer that you get on Windows, so it would be good if we could make it work.

**Comment by billhoffman** [comment]
Since castxml is a separate executable it really should not matter if it is built 32 or 64. I don't think there are 32 bit windows anymore so it should always work. If there is a way to fool the system into using the 64 bit castxml for a 32 bit pip install.

**Comment by jcfr** [comment]
Since there are no wheels available for 32-bit, this is expected. 
Generating windows package for 32-bit is now captured in https://github.com/CastXML/CastXMLSuperbuild/issues/38

**Comment by jcfr** [comment]
> I don't think there are 32 bit windows anymore so it should always work. 

Good point. 

I will add generation of windows 32-bit by packaging the 64-bit binaries

**Comment by jcfr** [comment]
>  Generating windows package for 32-bit is now captured in CastXML/CastXMLSuperbuild#38

Issue has been closed, we will re-package the 64-bit binary into the 32-bit wheel

**Comment by jcfr** [comment]
32-bit windows wheels are not available:

![image](https://user-images.githubusercontent.com/219043/90060345-94fb2d80-dcb2-11ea-9521-f67c78b3246c.png)

@billhoffman Could you try again ?

**Comment by josephsnyder** [comment]
A, previously manual process, to use the 64bit executable for the 32bit wheel has been codified in #11.  Closing
